services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: ["--log_bin_trust_function_creators=1", "--event-scheduler=ON"]
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_USER: challenge
      MYSQL_PASSWORD: challenge
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: "America/Argentina/Buenos_Aires"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - challenge-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 25

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/challenge
      SPRING_DATASOURCE_USERNAME: challenge
      SPRING_DATASOURCE_PASSWORD: challenge
      JWT_SECRET_KEY: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      SECURITY_JWT_EXPIRATION_TIME: 300050
      api-countries: ${API-COUNTRY}

    ports:
      - 8081:8081
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - challenge-network
volumes:
  mysql_data:

networks:
  challenge-network:
